apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana

patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: validate-k8s-monitoring
        namespace: monitoring
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: test-k8s-monitoring
        namespace: monitoring
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: validate-k8s-monitoring
        namespace: monitoring
  - patch: |-
      $patch: delete
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: test-k8s-monitoring
        namespace: monitoring
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: analyze-k8s-monitoring
        namespace: monitoring
