apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana

patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: StatefulSet
      name: k8s-monitoring-alloy-metrics

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: Deployment
      name: k8s-monitoring-alloy-singleton

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: DaemonSet
      name: k8s-monitoring-alloy-logs

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: DaemonSet
      name: k8s-monitoring-alloy-receiver

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: DaemonSet
      name: k8s-monitoring-kepler

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: DaemonSet
      name: k8s-monitoring-node-exporter

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: Deployment
      name: k8s-monitoring-kube-state-metrics
