apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana

patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: validate-k8s-monitoring
        namespace: monitoring
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: test-k8s-monitoring
        namespace: monitoring
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: validate-k8s-monitoring
        namespace: monitoring
  - patch: |-
      $patch: delete
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: test-k8s-monitoring
        namespace: monitoring
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: analyze-k8s-monitoring
        namespace: monitoring

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: StatefulSet
      name: k8s-monitoring-alloy

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: Deployment
      name: k8s-monitoring-alloy-events

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: DaemonSet
      name: k8s-monitoring-alloy-logs

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: DaemonSet
      name: k8s-monitoring-kepler

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: DaemonSet
      name: k8s-monitoring-prometheus-node-exporter

  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/resources"
        value:
          requests:
            cpu: "100m"
            memory: "200m"
    target:
      kind: Deployment
      name: k8s-monitoring-kube-state-metrics

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: k8s-monitoring-opencost
      spec:
        template:
          spec:
            containers:
              - name: k8s-monitoring-opencost
                env:
                  - name: DB_BASIC_AUTH_USERNAME
                    valueFrom:
                      secretKeyRef:
                        key: ${metrics_username_key}
                        name: ${metrics_secret}
                  - name: DB_BASIC_AUTH_PW
                    valueFrom:
                      secretKeyRef:
                        key: ${metrics_password_key}
                        name: ${metrics_secret}
                  - name: PROMETHEUS_SERVER_ENDPOINT
                    value: null
                    valueFrom:
                      secretKeyRef:
                        key: ${metrics_hostname_key}_prom
                        name: ${metrics_secret}
    target:
      kind: Deployment
      name: k8s-monitoring-opencost
