apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-k8s-monitoring
resources:
  - namespace.yaml
  - config.yaml
helmCharts:
  - name: k8s-monitoring
    namespace: monitoring
    repo: https://grafana.github.io/helm-charts
    version: 3.3.1
    releaseName: k8s-monitoring
    includeCRDs: true
    valuesFile: operator-values.yaml
