cluster:
  name: ${cluster_name}
destinations:
  metricsService:
    type: prometheus
    url: ${metrics_url}
    secret:
      create: false
      name: ${metrics_secret}
    auth:
      type: basic
      usernameKey: ${metrics_username_key}
      passwordKey: ${metrics_password_key}
  logsService:
    type: loki
    url: ${logs_url}
    secret:
      create: false
      name: ${logs_secret}
    auth:
      type: basic
      usernameKey: ${logs_username_key}
      passwordKey: ${logs_password_key}
  tracesService:
    type: otlp
    url: ${traces_host}
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
    secret:
      create: false
      name: ${traces_secret}
    auth:
      type: basic
      usernameKey: ${traces_username_key}
      passwordKey: ${traces_password_key}
clusterMetrics:
  enabled: true
costMetrics:
  enabled: true
hostMetrics:
  enabled: true
clusterEvents:
  enabled: true
podLogs:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      includeDebugMetrics: true
      grpc:
        enabled: true
      http:
        enabled: true
    zipkin:
      enabled: true
      includeDebugMetrics: true
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy
        metrics:
          tuning:
            useDefaultAllowList: true
            includeMetrics:
              - alloy_build_info
collectors:
  alloy:
    presets:
      - statefulset
    alloy:
      clustering:
        enabled: true
      extraPorts:
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-httpgrpc
          port: 4318
          targetPort: 4318
          protocol: TCP
        - name: zipkin
          port: 9411
          targetPort: 9411
          protocol: TCP
      resources:
        requests:
          memory: 400m
telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  opencost:
    deploy: true
    metricsSource: metricsService
    opencost:
      exporter:
        defaultClusterId: ${cluster_name}
      prometheus:
        external:
          url: ${cost_metrics_url}
        existingSecretName: ${metrics_secret}
        username_key: ${metrics_username_key}
        password_key: ${metrics_password_key}
  kepler:
    deploy: true
alloy-operator:
  deploy: true
  waitForAlloyRemoval:
    enabled: false
