cluster:
  name: ${cluster_name}
destinations:
  - name: metricsService
    url:  ${metrics_url}
    type: prometheus
    secret:
      create: false
      name: ${metrics_secret}
    auth:
      type: basic
      usernameKey: ${metrics_username_key}
      passwordKey: ${metrics_password_key}
  - name: logsService
    type: loki
    url:  ${logs_url}
    secret:
      create: false
      name: ${logs_secret}
    auth:
      type: basic
      usernameKey: ${logs_username_key}
      passwordKey: ${logs_password_key}
  - name: tracesService
    type: otlp
    url:  ${traces_host}
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
    secret:
      create: false
      name: ${traces_secret}
    auth:
      type: basic
      usernameKey: ${traces_username_key}
      passwordKey: ${traces_password_key}
clusterMetrics:
  enabled: true
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
    enabled: true
  opencost:
    enabled: true
    opencost:
      exporter:
        defaultClusterId: ${cluster_name}
      prometheus:
        external:
          url: ${cost_metrics_url}
        existingSecretName: ${metrics_secret}
        username_key: ${metrics_username_key}
        password_key: ${metrics_password_key}
    metricsSource: metricsService
  kepler:
    enabled: true
alloy-metrics:
  enabled: true
clusterEvents:
  enabled: true
alloy-singleton:
  enabled: true
podLogs:
  enabled: true
alloy-logs:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      includeDebugMetrics: true
      grpc:
        enabled: true
      http:
        enabled: true
    zipkin:
      enabled: true
      includeDebugMetrics: true
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-httpgrpc
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-logs
            - alloy-receiver
        metrics:
          tuning:
            useDefaultAllowList: true
            includeMetrics:
              - alloy_build_info
